### ISSUE TITLE
Unset the proxy.pac on graceful shutdown

### ISSUE THREAD

**Issue by Hacksore** [nickhudkins/malcolm#19]
title

**Comment by nickhudkins** [comment]
Damnit @Hacksore you should have tagged your last PR with this to auto-close it

**Comment by Hacksore** [comment]
@nickhudkins broski

https://github.com/nickhudkins/malcolm/blob/303a3362138259db3b27eeb6e138c2365670a17a/packages/proxy/src/program.ts#L39

**Comment by Hacksore** [comment]
I need a new issue for the above
